print("Hello there!")
print("In Python, Modules are a piece of code that contain specific functions that programmers can use for their convenience.")
print("\nThere are 2 types of Modules:")
print("First one are 'In-built Modules'. These are already present in Python and don't need to be installed. e.g. calendar, cmath, and haslib")
print("Second one are 'User-defined Modules' or 'External Modules'. They need to be installed. e.g. datetime, pandas, and tensorflow.")